# Project Details
### 1. Project Name:- Student Mark Prediction
### 2. Domain:- Education
### 3. Algorithm:- Linear Regression
### 4. Problem Type:- Regression
### 5. Tools:- Pandas, Numpy, Matpltolib, Seaborn, Scikitlearn
### 6. Objective:- On the basis of some inputs related to the study or performance, model predict the marks using linear regression...

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("All Important Library are imported Successfully!!")

Matplotlib is building the font cache; this may take a moment.

All Important Library are imported Successfully!!

In [11]:
df = pd.read_csv('dataset/Student_Performance.csv')
print("Dataset Loaded Successfully!")
df.head()

Dataset Loaded Successfully!

   Hours Studied  ...  Performance Index
0              7  ...               91.0
1              4  ...               65.0
2              8  ...               45.0
3              5  ...               36.0
4              7  ...               66.0

[5 rows x 6 columns]

In [12]:
df.shape

(10000, 6)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  str
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), str(1)
memory usage: 468.9 KB

* Our data has total 10000 records of student containing 6 features.
1. In our Dataset have total 6 columns, in which 4 are int dtype, 1 is string, and other 1 is float.
2. Our dataset look like clean as a null values, because our dataset not have any null values which saves our a single steps of handling the null values..
3. In this out of 6 we have 5 input column and 1 (Performance Index) is ouput column.

In [18]:
df.describe()

       Hours Studied  ...  Performance Index
count   10000.000000  ...       10000.000000
mean        4.992900  ...          55.224800
std         2.589309  ...          19.212558
min         1.000000  ...          10.000000
25%         3.000000  ...          40.000000
50%         5.000000  ...          55.000000
75%         7.000000  ...          71.000000
max         9.000000  ...         100.000000

[8 rows x 5 columns]

In [ ]:
df.duplicated().sum()
# The duplicate values apprx 1.27 percant of dataset it does not impacts the our output so we drop these duplicated.
df = df.drop_duplicates()
print("All Duplicates are removed for the dataset!")

All Duplicates are removed for the dataset!